#include <Arduino.h>
#include <eloquent_tensorflow_cortexm.h>

// Generated by train_export_glove_tflite_eloquent.py
#include "glove_fcnn_40_20_model_data.h"

// Must be large enough for your model tensors. Increase if begin() fails.
constexpr int kTensorArenaSize = 16 * 1024;
constexpr int kNumInputs = 2;
constexpr int kNumOutputs = 9;
constexpr int kNumOps = 10;
constexpr int kPinA1 = A1;
constexpr int kPinA0 = A0;
constexpr unsigned long kPredictPeriodMs = 80;

using Eloquent::CortexM::TensorFlow;
TensorFlow<kNumOps, kTensorArenaSize> tf;

// Copy these scaler values from Python script output after training.
// x_scaled = (x - mean) / scale
float scaler_mean[kNumInputs] = {429.55505f, 397.75505f};
float scaler_scale[kNumInputs] = {65.49874f, 85.82653f};

unsigned long last_predict_ms = 0;


void setup() {
  Serial.begin(115200);
  delay(1500);

  Serial.println("Selected NN architecture: FCNN (2 -> 40 -> 20 -> 9)");
  Serial.println("Initializing TensorFlow...");

  tf.setNumInputs(kNumInputs);
  tf.setNumOutputs(kNumOutputs);

  // Follow the same setup style as the known-good glove sketch.
  tf.resolver.AddFullyConnected();
  tf.resolver.AddRelu();
  tf.resolver.AddSoftmax();
  tf.resolver.AddQuantize();
  tf.resolver.AddDequantize();

  if (!tf.begin(g_glove_model).isOk()) {
    Serial.print("TF begin error: ");
    Serial.println(tf.exception.toString());
    Serial.println("HALT");
    while (true) {
      delay(1000);
    }
  }

  Serial.println("TinyML init OK");
  Serial.println("Input mode: analogRead(A1, A0) every 80 ms");
  Serial.println("Optional override: send two floats over Serial as A1 A0");
}


void loop() {
  const unsigned long now = millis();
  if (now - last_predict_ms < kPredictPeriodMs) {
    return;
  }
  last_predict_ms = now;

  float a1 = (float) analogRead(kPinA1);
  float a0 = (float) analogRead(kPinA0);

  // If user sends "A1 A0" over Serial, use that instead of analog pins.
  if (Serial.available()) {
    float s1 = Serial.parseFloat();
    float s0 = Serial.parseFloat();
    if (!(s1 == 0.0f && s0 == 0.0f && Serial.peek() == -1)) {
      a1 = s1;
      a0 = s0;
    }
  }

  float x[kNumInputs];
  x[0] = (a1 - scaler_mean[0]) / scaler_scale[0];
  x[1] = (a0 - scaler_mean[1]) / scaler_scale[1];

  // Use manual quantization with saturation to avoid int8 wrap-around.
  const float in_scale = tf.input->params.scale;
  const int in_zero = tf.input->params.zero_point;
  for (int i = 0; i < kNumInputs; i++) {
    int32_t q = (int32_t) roundf(x[i] / in_scale) + in_zero;
    if (q < -128) q = -128;
    if (q > 127) q = 127;
    tf.input->data.int8[i] = (int8_t) q;
  }

  if (tf.interpreter->Invoke() != kTfLiteOk) {
    Serial.println("TF invoke error");
    delay(30);
    return;
  }

  int pred = 0;
  int8_t best = tf.output->data.int8[0];
  for (int i = 1; i < kNumOutputs; i++) {
    int8_t v = tf.output->data.int8[i];
    if (v > best) {
      best = v;
      pred = i;
    }
  }

  Serial.print("A1: ");
  Serial.print(a1, 3);
  Serial.print(" A0: ");
  Serial.print(a0, 3);
  Serial.print(" -> pred: ");
  Serial.println(pred);

  delay(30);
}
